# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170407_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
